[package]
name = "simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.169"
xdrippi = "0.1.0"
shipcomponent = { path = "../shipcomponent"}
ship = { path = "../ship" }
policy_parser = { path = "../policy_parser" }
